services:
  - type: web
    name: womensafety-backend
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "jdbc:postgresql://dpg-cv0vjhtsvqrc73dsiju0-a.oregon-postgres.render.com/womensafetydb"
      - key: SPRING_DATASOURCE_USERNAME
        value: "womensafetydb_user"
      - key: SPRING_DATASOURCE_PASSWORD
        value: "IN85rPT4sdrGJHUfhw4JSAKbaL1ek4Hl"
    buildCommand: "./render-build.sh"
    startCommand: "java -jar target/*.jar"
